In [ ]:
import numpy as np
def calculateNeed(need, maxm, allot): 
    for i in range(P): 
        for j in range(R): 
            need[i][j] = maxm[i][j] - allot[i][j] 
def isSafe(processes, avail, maxm, allot): 
    need = [] 
    for i in range(P): 
        l = [] 
        for j in range(R): 
            l.append(0) 
        need.append(l) 
    calculateNeed(need, maxm, allot) 
    finish = [0] * P 
    safeSeq = [0] * P 
    work = [0] * R 
    for i in range(R): 
        work[i] = avail[i] 
    count = 0
    while (count < P): 
        found = False
        for p in range(P): 
            if (finish[p] == 0): 
                for j in range(R): 
                    if (need[p][j] > work[j]): 
                        break
                if (j == R - 1): 
                    for k in range(R): 
                        work[k] += allot[p][k] 
                    safeSeq[count] = p 
                    count += 1
                    finish[p] = 1
                    found = True
        if (found == False): 
            print("System is not in safe state") 
            return False

    print("System is in safe state.", 
            "\nSafe sequence is: ", end = " ") 
    print(*safeSeq) 

    return True

if __name__ =="__main__": 
    P = int(input("Enter the number of processes : "))
    R = int(input("Enter the number of resources : "))
   # P = 5
   # R = 3

    processes = []
    for counter in range(P):
        x = int(input(":"))
        processes.append(x)
    print(processes)
 
    avail = []
    for counter in range(R):
        x = int(input(":"))
        avail.append(x)
    print(avail)
 


    shape = (P,R)
    
    data = []
    for counter in range(P*R):
        x = int(input(":"))
        data.append(x)
        print(data)
    
    maxm = np.array(data).reshape(shape)

    print(maxm)

    
    data2 = []
    for counter in range(P*R):
        x = int(input(":"))
        data2.append(x)
        print(data2)
    
    allot = np.array(data2).reshape(shape)

    print(allot)
    
    isSafe(processes, avail, maxm, allot) 

Enter the number of processes : 5
Enter the number of resources : 3


In [7]:
shape = (5, 3)
    
data = []
for counter in range(15):
    x = int(input(":"))
    data.append(x)
    print(data)
    
data1 = np.array(data).reshape(shape)

print(data1)

:1
[1]
:1
[1, 1]
:1
[1, 1, 1]
:1
[1, 1, 1, 1]
:1
[1, 1, 1, 1, 1]
:1
[1, 1, 1, 1, 1, 1]
:1
[1, 1, 1, 1, 1, 1, 1]
:1
[1, 1, 1, 1, 1, 1, 1, 1]
:1
[1, 1, 1, 1, 1, 1, 1, 1, 1]
:1
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
:1
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
:1
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
:1
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
:1
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
:1
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
import numpy as np
def calculateNeed(need, max_need, allocation): 
    for i in range(no_of_processes): 
        for j in range(no_of_resources): 
            need[i][j] = max_need[i][j] - allocation[i][j] 

def check_safe_state(processes, available, max_need, allocation): 
    need = [] 
    
    for i in range(no_of_processes): 
        l = [] 
        for j in range(no_of_resources): 
            l.append(0) 
        need.append(l) 
    calculateNeed(need, max_need, allocation) 
    
    finish = [0] * no_of_processes 
    safeSeq = [0] * no_of_processes 
    work = [0] * no_of_resources 
    
    for i in range(no_of_resources): 
        work[i] = available[i] 
    
    count = 0
    
    while (count < no_of_processes): 
        found = False
        for p in range(no_of_processes): 
            if (finish[p] == 0): 
                for j in range(no_of_resources): 
                    if (need[p][j] > work[j]): 
                        break
                if (j == no_of_resources - 1): 
                    for k in range(no_of_resources): 
                        work[k] += allocation[p][k] 
                    safeSeq[count] = p 
                    count += 1
                    finish[p] = 1
                    found = True
        
        if (found == False): 
            print("System is not in safe state") 
            return False

    print("System is in safe state.", 
            "\nSafe sequence is: ", end = " ") 
    print(*safeSeq) 

    return True

if __name__ =="__main__": 
    no_of_processes = int(input("Enter the number of processes : "))
    no_of_resources = int(input("Enter the number of resources : "))
    processes = []
    for counter in range(no_of_processes):
        x = int(input(":"))
        processes.append(x)
    print(processes)
 
    available = []
    for counter in range(no_of_resources):
        x = int(input(":"))
        available.append(x)
    print(available)
 


    shape = (no_of_processes,no_of_resources)
    
    data = []
    for counter in range(no_of_processes*no_of_resources):
        x = int(input(":"))
        data.append(x)
        print(data)
    
    max_need = np.array(data).reshape(shape)

    print(max_need)

    
    data2 = []
    for counter in range(no_of_processes*no_of_resources):
        x = int(input(":"))
        data2.append(x)
        print(data2)
    
    allocation = np.array(data2).reshape(shape)

    print(allocation)
    

    #allocation = [[0, 1, 0], [2, 0, 0], 
     #       [3, 0, 2], [2, 1, 1], 
      #      [0, 0, 2]] 
    check_safe_state(processes, available, max_need, allocation) 

Enter the number of processes : 5
Enter the number of resources : 3
:0
:1
:2
:3
:4
[0, 1, 2, 3, 4]
:3
:3
:2
[3, 3, 2]


In [2]:
import numpy as np
def calculateNeed(need, max_need, allocation): 
    for i in range(no_of_processes): 
        for j in range(no_of_resources): 
            need[i][j] = max_need[i][j] - allocation[i][j] 

def check_safe_state(processes, available, max_need, allocation): 
    need = [] 
    
    for i in range(no_of_processes): 
        l = [] 
        for j in range(no_of_resources): 
            l.append(0) 
        need.append(l) 
    calculateNeed(need, max_need, allocation) 
    
    finish = [0] * no_of_processes 
    safeSeq = [0] * no_of_processes 
    work = [0] * no_of_resources 
    
    for i in range(no_of_resources): 
        work[i] = available[i] 
    
    count = 0
    
    while (count < no_of_processes): 
        found = False
        for p in range(no_of_processes): 
            if (finish[p] == 0): 
                for j in range(no_of_resources): 
                    if (need[p][j] > work[j]):   # this will detect deadlock
                        break
                if (j == no_of_resources - 1): 
                    for k in range(no_of_resources): 
                        work[k] += allocation[p][k] 
                    safeSeq[count] = p 
                    count += 1
                    finish[p] = 1
                    found = True
        
        if (found == False): 
            print("System is not in safe state") 
            return False

    print("System is in safe state.", 
            "\nSafe sequence is: ", end = " ") 
    print(*safeSeq) 

    return True

if __name__ =="__main__": 
    no_of_processes = int(input("Enter the number of processes : "))
    
    no_of_resources = int(input("Enter the number of resources : "))
    
    print("Enter the id of the processes : ")
    processes = []
    for counter in range(no_of_processes):
        x = int(input(":"))
        processes.append(x)
    print(processes)
 
    print("Enter the 1 X n matrix of available resources  i.e in the format res1_available, res2_available, .......resn_available : ")
    
    available = []
    for counter in range(no_of_resources):
        x = int(input(":"))
        available.append(x)
    print(available)
 
    shape = (no_of_processes,no_of_resources)
    
    print("Enter the maximum number of resources of each type needed for each process in the format : proc0_res1, proc0_res2........proc0_resn, ...........procm_res1, procm_res2,........procm_resn :")
    data = []
    for counter in range(no_of_processes*no_of_resources):
        x = int(input(":"))
        data.append(x)
        #print(data)
    
    max_need = np.array(data).reshape(shape)

    #print(max_need)
    
    print("Enter the alloted resources of each type for each process in the format : proc0_res1, proc0_res2........proc0_resn, ...........procm_res1, procm_res2,........procm_resn : ")
    
    data2 = []
    for counter in range(no_of_processes*no_of_resources):
        x = int(input(":"))
        data2.append(x)
        #print(data2)
    
    allocation = np.array(data2).reshape(shape)

    #print(allocation)
 
    check_safe_state(processes, available, max_need, allocation) 

Enter the number of processes : 5
Enter the number of resources : 3
Enter the id of the processes : 
:0
:1
:2
:3
:4
[0, 1, 2, 3, 4]
Enter the 1 X n matrix of available resources  i.e in the format res1_available, res2_available, .......resn_available : 
:3
:3
:2
[3, 3, 2]
Enter the maximum number of resources of each type needed for each process in the format : proc0_res1, proc0_res2........proc0_resn, ...........procm_res1, procm_res2,........procm_resn :
:7
:5
:3
:3
:2
:2
:9
:0
:2
:2
:2
:2
:4
:3
:3
Enter the alloted resources of each type for each process in the format : proc0_res1, proc0_res2........proc0_resn, ...........procm_res1, procm_res2,........procm_resn : 
:0
:1
:0
:2
:0
:0
:3
:0
:2
:2
:1
:1
:0
:0
:2
System is in safe state. 
Safe sequence is:  1 3 4 0 2
